server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogger?useSSL=false&serverTimezone=UTC
    username: root
    password: ll267896747
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
